config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: {
    :registrations => :registrations,
    :omniauth_callbacks => "omniauth_callbacks"
  }

  resources :parties

  as :user do
    get 'profile' => 'profile#show'
    get 'profile/edit', :to => 'profile#edit'
    put 'profile', :to => 'profile#update'
    get 'sign_out' => 'devise/sessions#destroy'
  end
end

app/models/party.rb
class Party < ActiveRecord::Base
  belongs_to :users

  geocoded_by :address
  after_validation :geocode

  validates :user_id, presence: true
  validates :title, presence: true
  validates :address, presence: true
  validates :min_age, presence: true

end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_party, only: [:show, :edit, :update, :destroy]
  before_action :current_location, only: [:index]
  before_action :latitude, only: [:index]
  before_action :longitude, only: [:index]

  def host?
    current_user.profile.host
  end

  def index
    parties_near_location
  end

  def parties_near_location
    if current_location.present?
      @parties = Party.near(current_location)
      build_map_markers
    else
      @parties = Party.all
      build_map_markers
    end
  end

  def show
  end

  def new
    if host?
      @party = Party.new
    else
      redirect_to parties_path, notice: 'You need to enable yourself as a host to create parties! Go to Settings.'
    end
  end

  def edit
  end

  def join_request
    if current_user.profile.guest == true
      ##
    else
      redirect_to parties_path, notice: 'You need to enable yourself as a guest to create parties! Go to Settings.'
    end
  end

  def create
    @party = Party.new(party_params)
    @party.user_id = current_user.id # assigns current user as party owner

    respond_to do |format|
      if @party.save
        format.html { redirect_to @party, notice: 'Party was successfully created.' }
        format.json { render :show, status: :created, location: @party }
      else
        format.html { render :new }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parties/1
  # PATCH/PUT /parties/1.json
  def update
    respond_to do |format|
      if @party.update(party_params)
        format.html { redirect_to @party, notice: 'Party was successfully updated.' }
        format.json { render :show, status: :ok, location: @party }
      else
        format.html { render :edit }
        format.json { render json: @party.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parties/1
  # DELETE /parties/1.json
  def destroy
    @party.destroy
    respond_to do |format|
      format.html { redirect_to parties_url, notice: 'Party was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected
    def party_params
      params.require(:party).permit(:user_id, :title, :address, :min_age, :description)
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_party
      @party = Party.find(params[:id])
    end

    def current_location
      if Rails.env.test? || Rails.env.development?
        @location ||= "Portland, OR"
      else
        @location ||= request.location.city
      end
    end

    def latitude
      coor = Geocoder.coordinates(current_location)
      @lat = coor[0]
    end

    def longitude
      coor = Geocoder.coordinates(current_location)
      @long = coor[1]
    end

    def build_map_markers
      @hash = Gmaps4rails.build_markers(@parties) do |party, marker|
        marker.lat party.latitude
        marker.lng party.longitude
      end
    end
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/helpers/party_helper.rb
module PartyHelper
end

app/views/parties/_form.html.haml
= form_for(@party) do |f|
  - if @party.errors.any?
    #error_explanation
      %h2
        = pluralize(@party.errors.count, "error")
        prohibited this party from being saved:
      %ul
        - @party.errors.full_messages.each do |message|
          %li= message
  .field
    .form-group
      = f.label :title, 'title'
      = f.text_field :title, class: 'form-control'
  .field
    .form-group
      = f.label :address, 'address'
      = f.text_field :address, class: 'form-control'
  .field
    .form-group
      = f.label :min_age, 'minimum age'
      = f.number_field :min_age, class: 'form-control'
  .field
    .form-group
      = f.label :description, 'description'
      = f.text_area :description, class: 'form-control'
  .actions.back
  -# if current_user.profile.host?
  = f.submit 'PARTAY!', class: 'btn btn-primary'
  %hr

app/views/parties/edit.html.haml
.container
  .col-md-4
    %h3= "Edit #{@party.title}"
    = render 'form'
    = link_to 'view', @party
    |
    = link_to 'back', parties_path

app/views/parties/index.html.haml
.container#party-index
  .col-md-4
    %h3
      %i.fa.fa-map-marker
      Parties Near You
      |
      = link_to 'create', new_party_path
    - @parties.each do |party|
      = link_to party do
        .party-container
          %h4.title= party.title
          %p.address= party.address
          %p.age= "Minimum Age: #{party.min_age}"
          %p= party.description
          -# if current_user is the host!
          -# = link_to 'Edit', edit_party_path(party)
          -# = link_to 'Destroy', party, method: :delete, data: { confirm: 'Are you sure?'
  .col-md-8
    #map{:style => "width: 1000px; height: 930px;"}
    %p= "Location: #{@location.inspect}"

= render 'partials/maps'

:javascript
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(#{raw @hash.to_json});
    handler.bounds.extendWith(markers);
    handler.getMap().setZoom(15);
    handler.getMap().setOptions({styles: styles});
    handler.getMap().setCenter(new google.maps.LatLng(#{@lat}, #{@long}));
  });

app/views/parties/new.html.haml
.container
  .col-md-4
    %h3 New Party
    = render 'form'
    = link_to '<< back', parties_path

app/views/parties/show.html.haml
-# this needs to be all cut3sy and show address on map
.container#party-index
  .col-md-4
    %p#notice= notice
    %p
      %strong Title:
      = @party.title
    %p
      %strong Address:
      = @party.address
    %p
      %strong Min age:
      = @party.min_age
    %p
      %strong Description:
      = @party.description
    -# if  current_user is the host, they can edit!
    = link_to 'edit', edit_party_path(@party)
    |
    = link_to 'back', parties_path