config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: {
    :registrations => :registrations,
    :omniauth_callbacks => "omniauth_callbacks"
  }

  resources :parties

  as :user do
    get 'profile' => 'profile#show'
    get 'profile/edit', :to => 'profile#edit'
    put 'profile', :to => 'profile#update'
    get 'sign_out' => 'devise/sessions#destroy'
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
.bGround
  %header.logo
    .wow.swing
      .container
        .row
          %h1 rCrowd
    .container
      .row
        .col-md-4.col-md-offset-4
          = form_for(:user, as: :user, url: session_path(:user)) do |f|
            .form-group
              = f.label :email, 'email'
              = f.text_field :email, autofocus: true, class: 'form-control'

            .form-group
              = f.label :password, 'password'
              = f.password_field :password, autocomplete: 'off', class: 'form-control'

            .form-group
              = link_to 'sign up', new_registration_path(:user)
              = f.label :remember_me, '| remember me'
              = f.check_box :remember_me

            .actions
              = f.submit 'submit', class: 'btn btn-primary'

            .form-group{style: "margin-top: 20px;"}
              = link_to image_tag("fb-login.png", width: '150'), user_omniauth_authorize_path(:facebook)
:javascript
  new WOW().init();